### ISSUE TITLE
请问一下这种报错一般是什么问题，该怎么解决？

### ISSUE THREAD

**Issue by OcrSu** [cap153/bili-sync-yt-dlp#2]
![image](https://github.com/user-attachments/assets/4f7c613f-c12d-4a32-b291-ad2579d43e37)
![image](https://github.com/user-attachments/assets/3995c403-82c2-4e06-9634-34f0f3d98ecf)

系统是FNOS

**Comment by cap153** [comment]
我有个[rust开发的yt-dlp客户端](https://www.bilibili.com/video/BV1Gs6mYYEXe/?spm_id_from=333.999.0.0&vd_source=670195c083a81e0e203115ecef2b87a1)也可以试试，[github地址](https://github.com/cap153/ydui)

**Comment by OcrSu** [comment]
> 我有个[rust开发的yt-dlp客户端](https://www.bilibili.com/video/BV1Gs6mYYEXe/?spm_id_from=333.999.0.0&vd_source=670195c083a81e0e203115ecef2b87a1)也可以试试，[github地址](https://github.com/cap153/ydui)

太猛了，可惜我完全不会rust，我的Python水准完全来源于我贫瘠的英文水准和基本逻辑 :)
这个issue图里的报错是因为 网络防火墙屏蔽掉了 bilibii的劣质PCDN线路导致的报错，程序本身没问题

**Comment by cap153** [comment]
来看我的rust写的[新项目](https://www.bilibili.com/video/BV1183ozEEUG/)，也是同步b站视频，解决了内存泄露等诸多问题，[github地址](https://github.com/cap153/bili-sync-fav)
