### ISSUE TITLE
多p视频保存时能否加上分p的名称？

### ISSUE THREAD

**Issue by bushadie** [cap153/bili-sync-yt-dlp#4]
多p视频保存时能否加上分p的名称？

**Comment by bushadie** [comment]
最好能单独创一个文件夹

**Comment by cap153** [comment]
> 最好能单独创一个文件夹

我原来就是单独创建文件夹的，后面发现用jellyfin扫描巨慢无比，就全部放在一个文件夹，用[K-Lite Codec Pack](https://codecguide.com/download_kl.htm)这个软件来扫描视频封面

**Comment by cap153** [comment]
> 多p视频保存时能否加上分p的名称？

多p视频我用_1，_2，_3来命名，平时我都是看视频封面来区分，暂时没有加上分p名称的意向

**Comment by cap153** [comment]
close as not planned

**Comment by cap153** [comment]
close as not planned

**Comment by cap153** [comment]
close as not planned
